baseURL = "https://www.thevacationator.com"
languageCode = "en-us"
title = "The Vacationator"
#theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
googleAnalytics = "UA-73238590-2"

[module]
    [[module.imports]]
        path = "github.com/theNewDynamic/gohugo-theme-ananke"

[params]
    # meta tag description
    description = """The Vacationator: RV Travel & Adventures \
                     in a converted Ford Transit all over the United States. \
                     Making vacations great again"""

    # https://themes.gohugo.io/themes/gohugo-theme-ananke/#update-font-or-body-classes
    body_classes = "sans-serif"
    background_color_class = "bg-near-black"
    site_logo = "img/logo.png"
